### PR TITLE
Funding fixes

### LINKED ISSUE #470: Validate: end of first reporting period is after or the same as enrollment date
**AC:**
- Validate that the last day of the child's first CDC reporting period is the same or after the child's enrollment date (e.g., if the start date is January 1, the reporting period can't be earlier than Jan 1-Jan 31; a child CAN enroll earlier than the funding/reporting start date)
- Error highlights enrollment date field ("Start date") with following copy:  
  - Reporting period must be after start date

### LINKED ISSUE #571: C4K date dropdown errors
Entering a family ID and invalid date for C4k funding stuff-- errors should update to accept family ID and say “invalid date”

### PR DESCRIPTION
**Pull request by cailyncodes**
This addresses all of the funding related issues in the QA list.

Working on identifying tickets. So far, should close #470, should close #571 

URL:...

### CODE REVIEW

File: src/Hedwig/ClientApp/src/utils/validations/processBlockingValidationErrors.ts [hunk 1]
```diff
@@ -3,7 +3,9 @@ export function processBlockingValidationErrors(field: string, errors?: { [key:
     return undefined;
   }
 
-  const fieldRegex = new RegExp(field.split('.').join('.*'), 'i');
+  // This matches object fields that are contained in an array
+  // e.g. fundings[1].familyid
+  const fieldRegex = new RegExp(`^${field.split('.').join('(\\[.*\\])?\.?')}$`, 'i');
```
Comment (jlhogan) [inline src/Hedwig/ClientApp/src/utils/validations/processBlockingValidationErrors.ts]: ty!!
