### PR TITLE
Fix roster link bug

### LINKED ISSUE #1205: After enrolling a child, back to roster link doesn't go back to roster
backtoroster

### PR DESCRIPTION
**Pull request by cailyncodes**
Should close #1205

### CODE REVIEW

File: src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx [hunk 1]
```diff
@@ -86,7 +88,15 @@ export default function EnrollmentDetail({
 	const enrollmentHistoryProps = getEnrollmentTimelineProps(enrollment);
 
 	return (
-		<CommonContainer backText="Back to roster">
+		<CommonContainer
+			backText="Back to roster"
+			backHref={
+				// If we just came from the enrollment step list, we want to return
```
Comment (mmazanec22) [inline src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx:94]: This comment is really clear, yay
