### PR TITLE
710 uncaught api error

### LINKED ISSUE #710: Alert 400s that are not shown on page
If you take #709 as an example, the server returns a 400 for a failed validation when trying to edit any information. However, as that validation is not shown on the current screen, the effect for a user is a silent fail. We should have a way of catching 400 validation errors that do not correspond to any field on the page, both to alert the user that something has gone wrong (probably using the validation message), as well as to throw some sort of exception for us so we know when this happens, as 400s will be a pretty common and expected error.

**AC:**
* When an enrollment validation fails but cannot be corrected by a field on the current page (i.e. no red text appears next to any field), the user should see an error.
  * Headline: "Something went wrong"
  * Body:
    > We couldn't save your changes because we detected a potential inconsistency in the data. This shouldn't have happened. Our team has been notified of the problem.
    >
    > You may still be able to update other children on your roster. Please wait to submit a report to OEC until the problem is fixed. For updates, contact oec-data-pilot@skylight.digital.
* An error is thrown and captured by Sentry. The error includes the validation that failed and the page on which the error occurred. It does not include any data from the record itself, which would by PII.

### PR DESCRIPTION
**Pull request by jlhogan**
Repurposes the `error` entity of `ApiState` from `useApi` to pass around errors for pages using the associated apistate entity and api mutate function for that entity. 

Adds handling for un-UI-handled errors 

closes #710

### CODE REVIEW

File: src/Hedwig/ClientApp/src/hooks/useApi.ts [hunk 1]
```diff
@@ -73,6 +76,27 @@ export default function useApi<TData>(
...
 
+  // Create error parsing function
+	const handleError = async (error: any) => {
+		let jsonResponse: Object | null = null;
+		try {
+			jsonResponse = JSON.parse(await error.text());
+		} catch {}
+
+		let apiError: ApiError | null = null;
+		if(jsonResponse) {
```
Comment (jlhogan) [inline src/Hedwig/ClientApp/src/hooks/useApi.ts]: this means that if the error thrown is not json-parse-able, the error obj will remain null

since we have an API spec, the only valid errors returned from the API are the types defined in the generated client models, which come from Json.

right now the only non-json error bodies we get back are the empty 403s, which happen in dev and staging, and I think are best ignored.

However i'm not sure that totally ignoring non-json errors is the right move here. Maybe we want to throw an error?

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.test.tsx [hunk 2]
```diff
@@ -0,0 +1,46 @@
+import React from 'react';
+import { render } from '@testing-library/react';
+import ChildInfo from './ChildInfo';
+import { DeepNonUndefineable } from '../../../utils/types';
+import { Enrollment } from '../../../generated';
+
+jest.mock('../../../hooks/useApi');
+
+describe('enrollment sections', () => {
```
Comment (jlhogan) [inline src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.test.tsx]: Stopped here (only doing these two section tests) b/c I don't know if this is the right way to be testing. So many random strings being matched. Is there an easy way to do this at a higher level? Visual snapshots on e2e tests?

File: src/Hedwig/ClientApp/src/containers/App/App.tsx [hunk 3]
```diff
@@ -27,10 +27,13 @@ const App: React.FC = () => {
...
 
-	const [loading, error, reports] = useApi(api => api.apiOrganizationsOrgIdReportsGet(params), [
-		user,
-		cacheInvalidator,
-	]);
+	const [loading, error, reports] = useApi(
+		api => api.apiOrganizationsOrgIdReportsGet(params),
+		[user, cacheInvalidator],
+		{
+			skip: !user,
```
Comment (cmgiven) [inline src/Hedwig/ClientApp/src/containers/App/App.tsx]: Yes!

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.test.tsx (hunk 2 above)
Comment (cmgiven) [reply src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.test.tsx]: I think this style works? Something like `Child.FirstName` seems fine to me. Small suggestion on the assert.

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.test.tsx [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+					error={{
+						errors: { 'Child.FirstName': ['error'] },
+						status: 400,
+					}}
+				/>
+			);
+
+			// TODO: the id needs to be updated-- this will probably mess things up
+			const firstNameErr = await findByText('This information is required for enrollment');
+			expect(firstNameErr.id).toBe('child-firstname-error');
```
Comment (cmgiven) [inline src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.test.tsx]: Checking the ID of the result seems indirect. I think this is closer to RTL idioms:

```suggestion
			const firstNameInput = getByLabelText('First name').closest('div');
			expect(firstNameInput).toHaveTextContent('This information is required for enrollment');
```

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx [hunk 5]
```diff
@@ -58,12 +59,32 @@ const ChildInfo: Section = {
...
+		const [hasAlertedOnError, setHasAlertedOnError] = useState(false);
+		useFocusFirstError([error]);
+		useEffect(() => {
+			if (error && !hasAlertedOnError) {
+				if (!isBlockingValidationError(error)) {
+					throw new Error(error.title || 'Unknown api error');
+				}
+				setAlerts([validationErrorAlert]);
+			}
+		}, [error, hasAlertedOnError]);
```
Comment (cmgiven) [inline src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx]: Took me too long to reason through this, not realizing that effects only happen _after_ render. Makes sense now.

File: src/Hedwig/ClientApp/src/utils/validations/errorForField.ts [hunk 6]
```diff
@@ -30,15 +33,23 @@ export function warningForField<T extends Validatable>(
...
-	const fieldError = processBlockingValidationErrors(fieldId, error.errors);
+	const fieldError = processBlockingValidationErrors(
+		fieldId,
+		(error as ValidationProblemDetails).errors
+	);
 
 	if (fieldError) {
+		if (!hasAlertedOnError) {
+			setHasAlertedOnError(true);
+		}
```
Comment (cmgiven) [inline src/Hedwig/ClientApp/src/utils/validations/errorForField.ts]: This seems unnecessary. Is there a reason not to just call `setHasAlertedOnError(true)`?

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx (hunk 5 above)
Comment (jlhogan) [reply src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx]: I think this should be abstracted into a common form or apiForm element for the app, where we can make descriptive function names and/or add more in-depth commenting, but didn't want to further beef up these already long files

File: src/Hedwig/ClientApp/src/utils/validations/errorForField.ts (hunk 6 above)
Comment (jlhogan) [reply src/Hedwig/ClientApp/src/utils/validations/errorForField.ts]: I thought i was getting an infinite rendering loop without it, but must have been from something else! will clean up.

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx (hunk 5 above)
Comment (cmgiven) [reply src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx]: Yup, that makes sense.
