### PR TITLE
872 fix withdrawal regressions

### LINKED ISSUE #872: remove duplicate information in WIthdrawal page
**AC**:
- Funding tag without time is first line in right column (vs comp below where time abbrev is included)
- `Enrollment: [pretty formatted time]` is next line in right column (vs comp below where it displays raw time, not formatted)
- fix alignment of enrollment end date label and input (should be stacked)
- Snapshot tests added for Withdrawal page

pasted image 0

design decision: https://docs.google.com/document/d/1G5_yfnFxo8XjtEZlC_GLJ0Suq9iQUPx7rM302py1Akg/edit?disco=AAAAJLfyHiU

### PR DESCRIPTION
**Pull request by mmazanec22**
Closes #872 and #912

### CODE REVIEW

File: src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx [hunk 1]
```diff
@@ -122,12 +122,9 @@ export default function Roster() {
...
 			),
-			symbol: (
-				<Tag
-					text={source}
-					color={fundingSourceDetails[source].colorToken}
-					className="position-relative top-neg-2px"
-				/>
+			symbol: generateFundingTag(
+				{ source: source as FundingSource },
+				{ includeTime: true, className: 'position-relative top-neg-2px' }
```
Comment (jlhogan) [inline src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx]: I don't think the roster legend should include time (it does not right now)
