### PR TITLE
Fix foster skipping and add test

### LINKED ISSUE #737: Enrolling a foster child does not skip income section
Expected behavior: When enrolling a child, I check the "lives with foster family" checkbox and click "Save." I expect to skip the Income Determination section. This no longer happens, appears to be a regression.

### PR DESCRIPTION
**Pull request by cailyncodes**
Should close #737 

Added a test for regression catching (which took way too long to add smh)

Bug was introduced in #603

### CODE REVIEW

File: src/Hedwig/ClientApp/src/components/StepList/StepList.tsx [hunk 1]
```diff
@@ -33,7 +33,6 @@ const mapStepsToInternalProps = function<T>(steps: StepProps<T>[], activeStep: s
 		} else {
 			status = externalStep.status(props);
 		}
-
```
Comment (cmgiven) [inline src/Hedwig/ClientApp/src/components/StepList/StepList.tsx]: Taking your aggression out on innocent whitespace, Cailyn?

File: src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.test.tsx [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+
+		const saveBtn = getByText(/Save/i);
+		fireEvent.click(saveBtn);
+
+		await wait();
+
+		expect(history.location.pathname).toMatch(/family-income/i)
+	});
+
+	it('skips family income section when lives with foster family is selected', async () => {
```
Comment (cmgiven) [inline src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.test.tsx]: This is real nice.

File: src/Hedwig/ClientApp/src/components/StepList/StepList.tsx (hunk 1 above)
Comment (cailyncodes) [reply src/Hedwig/ClientApp/src/components/StepList/StepList.tsx]: Oh haha - I went digging for the bug and must have deleted this line after adding a console.log, oops
