### PR TITLE
Fix missing info string

### LINKED ISSUE #1207: Enrollment detail needs to be loaded earlier for batch edit description
~Even though we're creating an empty family in the family info section, it doesn't save when you press save.  Potentially user is not defined yet when we're trying to get the org id?~

We're setting the description before making the enrollment detail get request, so it doesn't include family or sub objects when it first loads.  Fix is to include enrollment details on initial get for enrollments or make a separate endpoint.

### PR DESCRIPTION
**Pull request by mmazanec22**
Closes #1207

### CODE REVIEW

File: src/Hedwig/Models/Enrollment/EnrollmentSummaryDTO.cs [hunk 1]
```diff
@@ -5,6 +5,7 @@
 
 namespace Hedwig.Models
 {
+	// TODO: maybe remove this?
```
Comment (jlhogan) [inline src/Hedwig/Models/Enrollment/EnrollmentSummaryDTO.cs:8]: i would vote for clean it up!!! we have the code in version control should we want ot bring it back. but cleaning up kruft later is way less likely to happen imo.
