### PR TITLE
Fix missing info that was over zealous and dropdown bugs on income not disclosed

### LINKED ISSUE #622: Missing information icon shows in summary on complete enrollment/funding section
But only when there is a CDC funding (private pay not affected)

### PR DESCRIPTION
**Pull request by cailyncodes**
Should close #622

### CODE REVIEW

**Comment by cmgiven** [comment]
PR reviews appear to be broken at the moment, but here's my comment:

> Maybe some tests here? Throw some errors at the status and check that it only responds to fundings, ageGroup, and entry?
> 
> Good use of a comment to explain populating the funding type options.

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx [hunk 1]
```diff
@@ -321,7 +325,18 @@ const EnrollmentFunding: Section = {
 		const [fundingTypeOpts, setFundingTypeOpts] = useState<{ value: string; text: string }[]>([]);
 		useEffect(() => {
 			const orgFundingSpaces = idx(site, _ => _.organization.fundingSpaces);
-			if (!orgFundingSpaces || familyDeterminationNotDisclosed(enrollment)) return;
+			// If the organization has no funding spaces
+			// Or if the family income is not disclosed and no previous cdc funding had been entered
+			// We do not want to automatically delete data if it has already been entered
```
Comment (jlhogan) [inline src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx]: This comment is not totally clear -- is ```we do not want to automatically delete data if it has already been entered``` and explanation for why `!cdcFunding` is part of the condition? If so, i think that could be made more explicit. I think my brain is expecting this comment to include the description of what we do when this condition is met, not just explanation of the condition itself. something liek:
```
// If the organization has no funding spaces
// or the family income is not disclosed and no previous cdcFunding exists (need preserve prior funding state even if incorrect)
// then the only valid funding type is private pay 
```
