### PR TITLE
PrivatePay/Select default fix

### LINKED ISSUE #582: Update funding model to allow for nullable time and source

### PR DESCRIPTION
**Pull request by cailyncodes**
Should close #582

### CODE REVIEW

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx [hunk 1]
```diff
@@ -131,11 +122,13 @@ const EnrollmentFunding: Section = {
 		);
 	},
 
-	Form: ({ enrollment, mutate, callback }) => {
+	Form: ({ enrollment, mutate, callback, visitedSections }) => {
 		if (!enrollment) {
 			throw new Error('EnrollmentFunding rendered without an enrollment');
 		}
 
+		const initialLoad = visitedSections ? !visitedSections[EnrollmentFunding.key] : true;
```
Comment (cailyncodes) [inline src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx]: This should default to `false` otherwise I think there might be issues with private pay on an edit of an enrollment

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx [hunk 2]
```diff
@@ -40,7 +40,10 @@ const EnrollmentFunding: Section = {
 	key: 'enrollment-funding',
 	name: 'Enrollment and funding',
 	status: ({ enrollment }) =>
-		enrollment && sectionHasValidationErrors([enrollment, enrollment.fundings])
+		enrollment && (
+			sectionHasValidationErrors([enrollment, enrollment.fundings]) ||
+			!!(enrollment.fundings || []).find(funding => !funding.source)
```
Comment (jlhogan) [inline src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx]: why wouldn't this be captured by validationErrors ?

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx (hunk 1 above)
Comment (jlhogan) [reply src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx]: if visited sections is not a thing in enrollmentEdit then yes def

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx [hunk 3]
```diff
@@ -203,49 +197,94 @@ const EnrollmentFunding: Section = {
...
-					// The funding is to be updated, so add it back with the new values
-					updatedFundings.push({
-						...(currentCdcFunding as Funding), // currentCdcFunding will always be defined but typescript doesn't infer so
-						time: cdcFundingTime ? cdcFundingTime : undefined,
-						firstReportingPeriodId: cdcReportingPeriod ? cdcReportingPeriod.id : undefined,
-						firstReportingPeriod: cdcReportingPeriod,
-					});
-				} else {
-					// The funding is to be removed
+			// CDC REGION
```
Comment (jlhogan) [inline src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx]: lol

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx (hunk 2 above)
Comment (cailyncodes) [reply src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx]: I don't think we current have a validation for that -- i.e. saving without a funding doesn't cause missing info

Comment (jlhogan) [reply src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx]: saving without a funding is valid state -- private pay

File: src/Hedwig/Models/Funding.cs [hunk 4]
```diff
@@ -20,7 +20,7 @@ public class Funding : TemporalEntity, INonBlockingValidatableObject
     public Enrollment Enrollment { get; set; }
 
     [JsonConverter(typeof(StringEnumConverter))]
-    public FundingSource Source { get; set; }
+    public FundingSource? Source { get; set; }
```
Comment (jlhogan) [inline src/Hedwig/Models/Funding.cs]: won't you also need to remove `RequiredForFundingSource` on line 38, and then add missing info validations for these fields?

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx (hunk 2 above)
Comment (jlhogan) [reply src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx]: if you mean funding w/out source or time does not cause missing info, that's true. But those validations should be added

Comment (cailyncodes) [reply src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx]: Yeah I meant source and time -- the state of selecting `Select` has not validation errors yet (which is the state of having a funding with no source)

File: src/Hedwig/Models/Funding.cs (hunk 4 above)
Comment (cailyncodes) [reply src/Hedwig/Models/Funding.cs]: I don't think so -- line 38 (funding time) should not be affected by this (?)

Comment (jlhogan) [reply src/Hedwig/Models/Funding.cs]: oh duh b/c its only required for cdc fundings, so if source-less can also be time-less

File: src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx (hunk 2 above)
Comment (jlhogan) [reply src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx]: do you want me to add them and push to this branch ?

Comment (cailyncodes) [reply src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx]: I was thinking we could create a new PR for that -- but I'm about to hop on a call so feel free to tackle that here if you have time

Comment (jlhogan) [reply src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx]: done
