### PR TITLE
Fix horizontal bug

### LINKED ISSUE #1174: Spacing on Ethnicity field
image

### PR DESCRIPTION
**Pull request by cailyncodes**
Should close #1174

### CODE REVIEW

File: src/Hedwig/ClientApp/src/components/FieldSet/FieldSet.tsx [hunk 1]
```diff
@@ -80,8 +80,8 @@ export const FieldSet: React.FC<FieldSetProps> = ({
 				className={cx(
 					'grid-gap',
 					childrenGroupClassName,
-					{ 'grid-row flex-align-start': horizontal },
-					{ 'grid-col': !horizontal }
+					{ 'grid-row flex-align-start': !horizontal },
```
Comment (jlhogan) [inline src/Hedwig/ClientApp/src/components/FieldSet/FieldSet.tsx:83]: interesting... not what i expected (i mean, clearly since i did this in the first place :slightly_smiling_face: )  putting things in grid-row with flex align start makes them vertically aligned?
